bugzilla_credentials:
  bugzilla_uri:
  username:
  password:
github_credentials:
  username:
  password:
commit_monitor:
  bugzilla_product:
diff_checker:
  blacklisted_strings:
    matchers:
      - "redhat"
      - "cloudforms"
      - "rdu2"
      - "red hat"
  puts:
    except:
      - tools/
gemfile_checker:
  pr_contacts: []
  enabled_repos: []
github_notification_monitor:
  repo_names: []
travis_event:
  enabled_repos: []
