bugzilla_credentials:
  bugzilla_uri:
  username:
  password:
github_credentials:
  username:
  password:
commit_monitor:
  bugzilla_product:
diff_checker:
  redhat:
    severity: ":black_circle:"
  cloudforms:
    severity: ":black_circle:"
  rdu2:
    severity: ":black_circle:"
  red hat:
    severity: ":red_circle:"
    except:
      - spec/vcr_
  puts:
    except:
      - tools/
    severity: ":red_circle:"
gemfile_checker:
  pr_contacts: []
  enabled_repos: []
github_notification_monitor:
  repo_names: []
travis_event:
  enabled_repos: []
